language: python

sudo: false

python:
  - "2.7"

install:
  - pip install git+https://github.com/colab/colab/
  - pip install coveralls flake8 behave behave_django
  - pip install .

script:
  - python setup.py test
  - flake8 src/colab_gitlab
  - flake8 test

after_success:
  - coveralls
