language: python

sudo: false

python:
  - "2.7"

install:
  - pip install git+https://github.com/colab/colab.git@detach_super_archives
  - pip install coveralls flake8 behave behave_django
  - pip install .

script:
  - python setup.py test
  - flake8 src/colab_superarchives
  - flake8 tests

after_success:
  - coveralls
